// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2L02bwdRJsIwdGAC4eil1mss9uyuSn94',
    appId: '1:618874866017:android:fd09381be8c56601299d20',
    messagingSenderId: '618874866017',
    projectId: 'pointer-e0497',
    databaseURL: 'https://pointer-e0497.firebaseio.com',
    storageBucket: 'pointer-e0497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMAr_HbETKVpsJN99uiHofHeovdyp1S4',
    appId: '1:618874866017:ios:9fa4ab8503cdb082299d20',
    messagingSenderId: '618874866017',
    projectId: 'pointer-e0497',
    databaseURL: 'https://pointer-e0497.firebaseio.com',
    storageBucket: 'pointer-e0497.appspot.com',
    androidClientId: '618874866017-1u1boc5eidisc8k1icq7e3abv344usug.apps.googleusercontent.com',
    iosClientId: '618874866017-iq6aij27p5r6pbaj90o4vbpqtcg5sc0k.apps.googleusercontent.com',
    iosBundleId: 'com.aadi.flutter.pointerV2',
  );
}
